language: ruby
rvm:
  - "2.2.2"
services: mongodb
sudo: false
install:
  - ssh-keygen -t rsa -N '' -f ~/.ssh/id_rsa
  - cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
  - chmod 600 ~/.ssh/authorized_keys
  - ssh localhost ls
  - bundle install --jobs=3 --retry=3 --path=vendor/bundle
cache:
  directories:
    - vendor/bundle
before_script:
  - sleep 15
script: bundle exec rspec spec/models/host_spec.rb

